[workspace]
members = [
  "szr_web",
  "szr_diesel_logger",
  "szr_morph",
  "szr_features",
  "szr_tokenise",
  "szr_yomichan",
  "szr_templates",
  "szr_schema",
  "szr_diesel_macros",
  "szr_dict",
  "szr_epub",
  "szr_golden",
  "szr_source",
]
