CREATE TABLE lemmas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  spelling TEXT NOT NULL,
  -- empty for e.g. punctuation
  reading TEXT
);

CREATE TABLE variants (
  -- we assign this ourselves
  -- an alternative would be 1-n for each lemma + a pkey on the (id, lemma_id) pair
  id BIGINT,
  -- a variant is always a variant of some lemma
  lemma_id BIGINT NOT NULL,
  spelling TEXT NOT NULL,
  -- empty for e.g. punctuation
  reading TEXT
);

CREATE TABLE surface_forms (
  -- allow overriding
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  -- may not be known
  variant_id BIGINT NOT NULL,
  spelling TEXT NOT NULL,
  -- may not have a known one
  reading TEXT
);
