CREATE TABLE lemmas (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  spelling text NOT NULL,
  -- empty for e.g. punctuation
  reading text
);

CREATE TABLE variants (
  -- we assign this ourselves
  -- an alternative would be 1-n for each lemma
  -- + a pkey on the (id, lemma_id) pair
  id bigint NOT NULL,
  -- a variant is always a variant of some lemma
  lemma_id bigint NOT NULL,
  spelling text NOT NULL,
  -- empty for e.g. punctuation
  reading text
);

CREATE TABLE surface_forms (
  -- allow overriding
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  -- may not be known
  variant_id bigint NOT NULL,
  spelling text NOT NULL,
  -- may not have a known one
  reading text
);

