-- lemmas are primarily a way for us to look things up in dictionaries
-- or to normalise etc

CREATE TABLE lemmas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  spelling TEXT NOT NULL,
  -- empty for e.g. punctuation
  reading TEXT
);

CREATE UNIQUE INDEX lemmas_spelling_reading ON lemmas (spelling, reading) INCLUDE (id);

-- the user dictionary is for adding new surface forms, not lemmas!

CREATE TABLE surface_forms (
  -- allow overriding
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  -- may not be known
  lemma_id BIGINT REFERENCES lemmas (id),
  spelling TEXT NOT NULL,
  -- may not have a known one
  reading TEXT
);

COMMENT ON TABLE surface_forms IS 'Surface forms (Unidic and custom)';

CREATE INDEX surface_forms_spelling_reading ON surface_forms (spelling, reading) INCLUDE (id);

CREATE TABLE defs (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  -- TODO separate dicts table
  dict_name TEXT NOT NULL,
  spelling TEXT NOT NULL,
  reading TEXT NOT NULL,
  content JSONB NOT NULL
);

CREATE INDEX defs_spelling_reading ON defs (spelling, reading);

CREATE TABLE books (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title TEXT NOT NULL
  -- author, cover, reading_progress, etc
);
