CREATE TABLE docs (
  id int GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL
);

CREATE TABLE lines (
  id int GENERATED BY DEFAULT AS IDENTITY,
  doc_id int NOT NULL, -- fk to docs (id)
  index int NOT NULL,
  content text NOT NULL
);
