[package]
name = "szr_web"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
szr_diesel_logger = { path = "../szr_diesel_logger" }
bincode = "1.3.3"
diesel = { version = "2.1.4", features = ["postgres"] }
serde = "1.0.193"
serde_json = "1.0.108"
test-log = { version = "0.2.13", features = ["trace"], default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
