[package]
name = "szr_web"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
szr_diesel_logger = { path = "../szr_diesel_logger" }
# szr_jagger = { path = "../szr_jagger" }
szr_features = { path = "../szr_features" }
szr_morph = { path = "../szr_morph" }
szr_tokenise = { path = "../szr_tokenise" }
bincode = "1.3.3"
diesel = { version = "2.1.4", features = ["postgres", "serde_json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
test-log = { version = "0.2.13", features = ["trace"], default-features = false }
time = { version = "0.3.30", features = ["formatting", "local-offset", "serde", "serde-human-readable", "macros"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "time", "local-time"] }
snafu = { version = "0.7.5", features = ["backtrace"] }
