[package]
name = "szr_jagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.7.5"
tracing = "0.1.40"
vaporetto = "0.6.3"
zstd = "0.13.0"
